/*******************************************************************************
 * See the NOTICE file distributed with this work for additional 
 * information regarding copyright ownership. ComicGenie licenses this 
 * file to you under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License.  
 * You may obtain a copy of the License at
 *  
 *     http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package org.comicwiki.model;

import java.util.Collection;
import java.util.HashSet;

import org.comicwiki.model.schema.Thing;

public class ComicIssueNumber extends Thing {

	
	//(2) cover
	
	//4/2009 - break this into issueNumber=4 and publicationYear = 2009
	
	//[1] - non numbered but this is number in sequence
	
	//1 cover
	
	//1 (2) indicia (cover)
	
	// 1 [2] - indicia [additional_number]
	
	/**
	 * indicia or cover or index or date
	 */
	public String referenceNumber;
	
	//no bracket, no parenthesis
	public String coverNumber;
	
	// 60 / 9
	public Collection<String> indiciaNumber = new HashSet<>();
	
	/**
	 * Generated by user or indexer;
	 */
	public int indexerNumber;

	
	/**
	 * non-numbered may also include inferred number [2] - sequenceNumber
	 */
	public boolean nonNumbered;//[nn]
}
